#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCSDL_Nhom15
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanBanh")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertT1_Bảng_Loại_Bánh(T1_Bảng_Loại_Bánh instance);
    partial void UpdateT1_Bảng_Loại_Bánh(T1_Bảng_Loại_Bánh instance);
    partial void DeleteT1_Bảng_Loại_Bánh(T1_Bảng_Loại_Bánh instance);
    partial void InsertT2_Bảng_Bánh(T2_Bảng_Bánh instance);
    partial void UpdateT2_Bảng_Bánh(T2_Bảng_Bánh instance);
    partial void DeleteT2_Bảng_Bánh(T2_Bảng_Bánh instance);
    partial void InsertT3_Bảng_KH(T3_Bảng_KH instance);
    partial void UpdateT3_Bảng_KH(T3_Bảng_KH instance);
    partial void DeleteT3_Bảng_KH(T3_Bảng_KH instance);
    partial void InsertT4_Bảng_NV(T4_Bảng_NV instance);
    partial void UpdateT4_Bảng_NV(T4_Bảng_NV instance);
    partial void DeleteT4_Bảng_NV(T4_Bảng_NV instance);
    partial void InsertT5_hóa_đơn(T5_hóa_đơn instance);
    partial void UpdateT5_hóa_đơn(T5_hóa_đơn instance);
    partial void DeleteT5_hóa_đơn(T5_hóa_đơn instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LTCSDL_Nhom15.Properties.Settings.Default.QuanLyBanBanhConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T1_Bảng_Loại_Bánh> T1_Bảng_Loại_Bánhs
		{
			get
			{
				return this.GetTable<T1_Bảng_Loại_Bánh>();
			}
		}
		
		public System.Data.Linq.Table<T2_Bảng_Bánh> T2_Bảng_Bánhs
		{
			get
			{
				return this.GetTable<T2_Bảng_Bánh>();
			}
		}
		
		public System.Data.Linq.Table<T3_Bảng_KH> T3_Bảng_KHs
		{
			get
			{
				return this.GetTable<T3_Bảng_KH>();
			}
		}
		
		public System.Data.Linq.Table<T4_Bảng_NV> T4_Bảng_NVs
		{
			get
			{
				return this.GetTable<T4_Bảng_NV>();
			}
		}
		
		public System.Data.Linq.Table<T5_hóa_đơn> T5_hóa_đơns
		{
			get
			{
				return this.GetTable<T5_hóa_đơn>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[T1_Bảng Loại Bánh]")]
	public partial class T1_Bảng_Loại_Bánh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_LB;
		
		private string _Tên;
		
		private EntitySet<T2_Bảng_Bánh> _T2_Bảng_Bánhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_LBChanging(string value);
    partial void OnMã_LBChanged();
    partial void OnTênChanging(string value);
    partial void OnTênChanged();
    #endregion
		
		public T1_Bảng_Loại_Bánh()
		{
			this._T2_Bảng_Bánhs = new EntitySet<T2_Bảng_Bánh>(new Action<T2_Bảng_Bánh>(this.attach_T2_Bảng_Bánhs), new Action<T2_Bảng_Bánh>(this.detach_T2_Bảng_Bánhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã LB]", Storage="_Mã_LB", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_LB
		{
			get
			{
				return this._Mã_LB;
			}
			set
			{
				if ((this._Mã_LB != value))
				{
					this.OnMã_LBChanging(value);
					this.SendPropertyChanging();
					this._Mã_LB = value;
					this.SendPropertyChanged("Mã_LB");
					this.OnMã_LBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tên", DbType="NVarChar(50)")]
		public string Tên
		{
			get
			{
				return this._Tên;
			}
			set
			{
				if ((this._Tên != value))
				{
					this.OnTênChanging(value);
					this.SendPropertyChanging();
					this._Tên = value;
					this.SendPropertyChanged("Tên");
					this.OnTênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T1_Bảng_Loại_Bánh_T2_Bảng_Bánh", Storage="_T2_Bảng_Bánhs", ThisKey="Mã_LB", OtherKey="Mã_LB")]
		public EntitySet<T2_Bảng_Bánh> T2_Bảng_Bánhs
		{
			get
			{
				return this._T2_Bảng_Bánhs;
			}
			set
			{
				this._T2_Bảng_Bánhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_T2_Bảng_Bánhs(T2_Bảng_Bánh entity)
		{
			this.SendPropertyChanging();
			entity.T1_Bảng_Loại_Bánh = this;
		}
		
		private void detach_T2_Bảng_Bánhs(T2_Bảng_Bánh entity)
		{
			this.SendPropertyChanging();
			entity.T1_Bảng_Loại_Bánh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[T2_Bảng Bánh]")]
	public partial class T2_Bảng_Bánh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_Bánh;
		
		private string _Tên_bánh;
		
		private string _Mã_LB;
		
		private string _Giá;
		
		private EntitySet<T5_hóa_đơn> _T5_hóa_đơns;
		
		private EntityRef<T1_Bảng_Loại_Bánh> _T1_Bảng_Loại_Bánh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_BánhChanging(string value);
    partial void OnMã_BánhChanged();
    partial void OnTên_bánhChanging(string value);
    partial void OnTên_bánhChanged();
    partial void OnMã_LBChanging(string value);
    partial void OnMã_LBChanged();
    partial void OnGiáChanging(string value);
    partial void OnGiáChanged();
    #endregion
		
		public T2_Bảng_Bánh()
		{
			this._T5_hóa_đơns = new EntitySet<T5_hóa_đơn>(new Action<T5_hóa_đơn>(this.attach_T5_hóa_đơns), new Action<T5_hóa_đơn>(this.detach_T5_hóa_đơns));
			this._T1_Bảng_Loại_Bánh = default(EntityRef<T1_Bảng_Loại_Bánh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã Bánh]", Storage="_Mã_Bánh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_Bánh
		{
			get
			{
				return this._Mã_Bánh;
			}
			set
			{
				if ((this._Mã_Bánh != value))
				{
					this.OnMã_BánhChanging(value);
					this.SendPropertyChanging();
					this._Mã_Bánh = value;
					this.SendPropertyChanged("Mã_Bánh");
					this.OnMã_BánhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên bánh]", Storage="_Tên_bánh", DbType="NVarChar(50)")]
		public string Tên_bánh
		{
			get
			{
				return this._Tên_bánh;
			}
			set
			{
				if ((this._Tên_bánh != value))
				{
					this.OnTên_bánhChanging(value);
					this.SendPropertyChanging();
					this._Tên_bánh = value;
					this.SendPropertyChanged("Tên_bánh");
					this.OnTên_bánhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã LB]", Storage="_Mã_LB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mã_LB
		{
			get
			{
				return this._Mã_LB;
			}
			set
			{
				if ((this._Mã_LB != value))
				{
					this.OnMã_LBChanging(value);
					this.SendPropertyChanging();
					this._Mã_LB = value;
					this.SendPropertyChanged("Mã_LB");
					this.OnMã_LBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giá", DbType="VarChar(50)")]
		public string Giá
		{
			get
			{
				return this._Giá;
			}
			set
			{
				if ((this._Giá != value))
				{
					this.OnGiáChanging(value);
					this.SendPropertyChanging();
					this._Giá = value;
					this.SendPropertyChanged("Giá");
					this.OnGiáChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T2_Bảng_Bánh_T5_hóa_đơn", Storage="_T5_hóa_đơns", ThisKey="Mã_Bánh", OtherKey="Mã_Bánh")]
		public EntitySet<T5_hóa_đơn> T5_hóa_đơns
		{
			get
			{
				return this._T5_hóa_đơns;
			}
			set
			{
				this._T5_hóa_đơns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T1_Bảng_Loại_Bánh_T2_Bảng_Bánh", Storage="_T1_Bảng_Loại_Bánh", ThisKey="Mã_LB", OtherKey="Mã_LB", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public T1_Bảng_Loại_Bánh T1_Bảng_Loại_Bánh
		{
			get
			{
				return this._T1_Bảng_Loại_Bánh.Entity;
			}
			set
			{
				T1_Bảng_Loại_Bánh previousValue = this._T1_Bảng_Loại_Bánh.Entity;
				if (((previousValue != value) 
							|| (this._T1_Bảng_Loại_Bánh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._T1_Bảng_Loại_Bánh.Entity = null;
						previousValue.T2_Bảng_Bánhs.Remove(this);
					}
					this._T1_Bảng_Loại_Bánh.Entity = value;
					if ((value != null))
					{
						value.T2_Bảng_Bánhs.Add(this);
						this._Mã_LB = value.Mã_LB;
					}
					else
					{
						this._Mã_LB = default(string);
					}
					this.SendPropertyChanged("T1_Bảng_Loại_Bánh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_T5_hóa_đơns(T5_hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.T2_Bảng_Bánh = this;
		}
		
		private void detach_T5_hóa_đơns(T5_hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.T2_Bảng_Bánh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[T3_Bảng KH]")]
	public partial class T3_Bảng_KH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_KH;
		
		private string _Họ_tên;
		
		private System.Nullable<System.DateTime> _Ngày_sinh;
		
		private string _Số_ĐT;
		
		private string _Địa_chỉ;
		
		private EntitySet<T5_hóa_đơn> _T5_hóa_đơns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_KHChanging(string value);
    partial void OnMã_KHChanged();
    partial void OnHọ_tênChanging(string value);
    partial void OnHọ_tênChanged();
    partial void OnNgày_sinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgày_sinhChanged();
    partial void OnSố_ĐTChanging(string value);
    partial void OnSố_ĐTChanged();
    partial void OnĐịa_chỉChanging(string value);
    partial void OnĐịa_chỉChanged();
    #endregion
		
		public T3_Bảng_KH()
		{
			this._T5_hóa_đơns = new EntitySet<T5_hóa_đơn>(new Action<T5_hóa_đơn>(this.attach_T5_hóa_đơns), new Action<T5_hóa_đơn>(this.detach_T5_hóa_đơns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã KH]", Storage="_Mã_KH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_KH
		{
			get
			{
				return this._Mã_KH;
			}
			set
			{
				if ((this._Mã_KH != value))
				{
					this.OnMã_KHChanging(value);
					this.SendPropertyChanging();
					this._Mã_KH = value;
					this.SendPropertyChanged("Mã_KH");
					this.OnMã_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Họ tên]", Storage="_Họ_tên", DbType="NVarChar(50)")]
		public string Họ_tên
		{
			get
			{
				return this._Họ_tên;
			}
			set
			{
				if ((this._Họ_tên != value))
				{
					this.OnHọ_tênChanging(value);
					this.SendPropertyChanging();
					this._Họ_tên = value;
					this.SendPropertyChanged("Họ_tên");
					this.OnHọ_tênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngày sinh]", Storage="_Ngày_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngày_sinh
		{
			get
			{
				return this._Ngày_sinh;
			}
			set
			{
				if ((this._Ngày_sinh != value))
				{
					this.OnNgày_sinhChanging(value);
					this.SendPropertyChanging();
					this._Ngày_sinh = value;
					this.SendPropertyChanged("Ngày_sinh");
					this.OnNgày_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Số ĐT]", Storage="_Số_ĐT", DbType="NChar(10)")]
		public string Số_ĐT
		{
			get
			{
				return this._Số_ĐT;
			}
			set
			{
				if ((this._Số_ĐT != value))
				{
					this.OnSố_ĐTChanging(value);
					this.SendPropertyChanging();
					this._Số_ĐT = value;
					this.SendPropertyChanged("Số_ĐT");
					this.OnSố_ĐTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Địa chỉ]", Storage="_Địa_chỉ", DbType="NVarChar(50)")]
		public string Địa_chỉ
		{
			get
			{
				return this._Địa_chỉ;
			}
			set
			{
				if ((this._Địa_chỉ != value))
				{
					this.OnĐịa_chỉChanging(value);
					this.SendPropertyChanging();
					this._Địa_chỉ = value;
					this.SendPropertyChanged("Địa_chỉ");
					this.OnĐịa_chỉChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T3_Bảng_KH_T5_hóa_đơn", Storage="_T5_hóa_đơns", ThisKey="Mã_KH", OtherKey="Mã_KH")]
		public EntitySet<T5_hóa_đơn> T5_hóa_đơns
		{
			get
			{
				return this._T5_hóa_đơns;
			}
			set
			{
				this._T5_hóa_đơns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_T5_hóa_đơns(T5_hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.T3_Bảng_KH = this;
		}
		
		private void detach_T5_hóa_đơns(T5_hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.T3_Bảng_KH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[T4_Bảng NV]")]
	public partial class T4_Bảng_NV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_NV;
		
		private string _Họ_tên;
		
		private System.Nullable<System.DateTime> _Ngày_sinh;
		
		private string _Số_DT;
		
		private string _Địa_chỉ;
		
		private string _Giới_Tính;
		
		private string _Chức_vụ;
		
		private EntitySet<T5_hóa_đơn> _T5_hóa_đơns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_NVChanging(string value);
    partial void OnMã_NVChanged();
    partial void OnHọ_tênChanging(string value);
    partial void OnHọ_tênChanged();
    partial void OnNgày_sinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgày_sinhChanged();
    partial void OnSố_DTChanging(string value);
    partial void OnSố_DTChanged();
    partial void OnĐịa_chỉChanging(string value);
    partial void OnĐịa_chỉChanged();
    partial void OnGiới_TínhChanging(string value);
    partial void OnGiới_TínhChanged();
    partial void OnChức_vụChanging(string value);
    partial void OnChức_vụChanged();
    #endregion
		
		public T4_Bảng_NV()
		{
			this._T5_hóa_đơns = new EntitySet<T5_hóa_đơn>(new Action<T5_hóa_đơn>(this.attach_T5_hóa_đơns), new Action<T5_hóa_đơn>(this.detach_T5_hóa_đơns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã NV]", Storage="_Mã_NV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_NV
		{
			get
			{
				return this._Mã_NV;
			}
			set
			{
				if ((this._Mã_NV != value))
				{
					this.OnMã_NVChanging(value);
					this.SendPropertyChanging();
					this._Mã_NV = value;
					this.SendPropertyChanged("Mã_NV");
					this.OnMã_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Họ tên]", Storage="_Họ_tên", DbType="NVarChar(50)")]
		public string Họ_tên
		{
			get
			{
				return this._Họ_tên;
			}
			set
			{
				if ((this._Họ_tên != value))
				{
					this.OnHọ_tênChanging(value);
					this.SendPropertyChanging();
					this._Họ_tên = value;
					this.SendPropertyChanged("Họ_tên");
					this.OnHọ_tênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngày sinh]", Storage="_Ngày_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngày_sinh
		{
			get
			{
				return this._Ngày_sinh;
			}
			set
			{
				if ((this._Ngày_sinh != value))
				{
					this.OnNgày_sinhChanging(value);
					this.SendPropertyChanging();
					this._Ngày_sinh = value;
					this.SendPropertyChanged("Ngày_sinh");
					this.OnNgày_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Số DT]", Storage="_Số_DT", DbType="NChar(10)")]
		public string Số_DT
		{
			get
			{
				return this._Số_DT;
			}
			set
			{
				if ((this._Số_DT != value))
				{
					this.OnSố_DTChanging(value);
					this.SendPropertyChanging();
					this._Số_DT = value;
					this.SendPropertyChanged("Số_DT");
					this.OnSố_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Địa chỉ]", Storage="_Địa_chỉ", DbType="NVarChar(50)")]
		public string Địa_chỉ
		{
			get
			{
				return this._Địa_chỉ;
			}
			set
			{
				if ((this._Địa_chỉ != value))
				{
					this.OnĐịa_chỉChanging(value);
					this.SendPropertyChanging();
					this._Địa_chỉ = value;
					this.SendPropertyChanged("Địa_chỉ");
					this.OnĐịa_chỉChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Giới Tính]", Storage="_Giới_Tính", DbType="NVarChar(50)")]
		public string Giới_Tính
		{
			get
			{
				return this._Giới_Tính;
			}
			set
			{
				if ((this._Giới_Tính != value))
				{
					this.OnGiới_TínhChanging(value);
					this.SendPropertyChanging();
					this._Giới_Tính = value;
					this.SendPropertyChanged("Giới_Tính");
					this.OnGiới_TínhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Chức vụ]", Storage="_Chức_vụ", DbType="NVarChar(50)")]
		public string Chức_vụ
		{
			get
			{
				return this._Chức_vụ;
			}
			set
			{
				if ((this._Chức_vụ != value))
				{
					this.OnChức_vụChanging(value);
					this.SendPropertyChanging();
					this._Chức_vụ = value;
					this.SendPropertyChanged("Chức_vụ");
					this.OnChức_vụChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T4_Bảng_NV_T5_hóa_đơn", Storage="_T5_hóa_đơns", ThisKey="Mã_NV", OtherKey="Mã_NV")]
		public EntitySet<T5_hóa_đơn> T5_hóa_đơns
		{
			get
			{
				return this._T5_hóa_đơns;
			}
			set
			{
				this._T5_hóa_đơns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_T5_hóa_đơns(T5_hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.T4_Bảng_NV = this;
		}
		
		private void detach_T5_hóa_đơns(T5_hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.T4_Bảng_NV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[T5_hóa đơn]")]
	public partial class T5_hóa_đơn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_HĐ;
		
		private string _Mã_NV;
		
		private string _Mã_KH;
		
		private System.Nullable<System.DateTime> _Ngày_đặt;
		
		private string _Tổng_tiền;
		
		private string _Bánh_mua;
		
		private string _Mã_Bánh;
		
		private EntityRef<T2_Bảng_Bánh> _T2_Bảng_Bánh;
		
		private EntityRef<T3_Bảng_KH> _T3_Bảng_KH;
		
		private EntityRef<T4_Bảng_NV> _T4_Bảng_NV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_HĐChanging(string value);
    partial void OnMã_HĐChanged();
    partial void OnMã_NVChanging(string value);
    partial void OnMã_NVChanged();
    partial void OnMã_KHChanging(string value);
    partial void OnMã_KHChanged();
    partial void OnNgày_đặtChanging(System.Nullable<System.DateTime> value);
    partial void OnNgày_đặtChanged();
    partial void OnTổng_tiềnChanging(string value);
    partial void OnTổng_tiềnChanged();
    partial void OnBánh_muaChanging(string value);
    partial void OnBánh_muaChanged();
    partial void OnMã_BánhChanging(string value);
    partial void OnMã_BánhChanged();
    #endregion
		
		public T5_hóa_đơn()
		{
			this._T2_Bảng_Bánh = default(EntityRef<T2_Bảng_Bánh>);
			this._T3_Bảng_KH = default(EntityRef<T3_Bảng_KH>);
			this._T4_Bảng_NV = default(EntityRef<T4_Bảng_NV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã HĐ]", Storage="_Mã_HĐ", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_HĐ
		{
			get
			{
				return this._Mã_HĐ;
			}
			set
			{
				if ((this._Mã_HĐ != value))
				{
					this.OnMã_HĐChanging(value);
					this.SendPropertyChanging();
					this._Mã_HĐ = value;
					this.SendPropertyChanged("Mã_HĐ");
					this.OnMã_HĐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã NV]", Storage="_Mã_NV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mã_NV
		{
			get
			{
				return this._Mã_NV;
			}
			set
			{
				if ((this._Mã_NV != value))
				{
					this.OnMã_NVChanging(value);
					this.SendPropertyChanging();
					this._Mã_NV = value;
					this.SendPropertyChanged("Mã_NV");
					this.OnMã_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã KH]", Storage="_Mã_KH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mã_KH
		{
			get
			{
				return this._Mã_KH;
			}
			set
			{
				if ((this._Mã_KH != value))
				{
					this.OnMã_KHChanging(value);
					this.SendPropertyChanging();
					this._Mã_KH = value;
					this.SendPropertyChanged("Mã_KH");
					this.OnMã_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngày đặt]", Storage="_Ngày_đặt", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngày_đặt
		{
			get
			{
				return this._Ngày_đặt;
			}
			set
			{
				if ((this._Ngày_đặt != value))
				{
					this.OnNgày_đặtChanging(value);
					this.SendPropertyChanging();
					this._Ngày_đặt = value;
					this.SendPropertyChanged("Ngày_đặt");
					this.OnNgày_đặtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tổng tiền]", Storage="_Tổng_tiền", DbType="NChar(10)")]
		public string Tổng_tiền
		{
			get
			{
				return this._Tổng_tiền;
			}
			set
			{
				if ((this._Tổng_tiền != value))
				{
					this.OnTổng_tiềnChanging(value);
					this.SendPropertyChanging();
					this._Tổng_tiền = value;
					this.SendPropertyChanged("Tổng_tiền");
					this.OnTổng_tiềnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bánh mua]", Storage="_Bánh_mua", DbType="NVarChar(50)")]
		public string Bánh_mua
		{
			get
			{
				return this._Bánh_mua;
			}
			set
			{
				if ((this._Bánh_mua != value))
				{
					this.OnBánh_muaChanging(value);
					this.SendPropertyChanging();
					this._Bánh_mua = value;
					this.SendPropertyChanged("Bánh_mua");
					this.OnBánh_muaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã Bánh]", Storage="_Mã_Bánh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mã_Bánh
		{
			get
			{
				return this._Mã_Bánh;
			}
			set
			{
				if ((this._Mã_Bánh != value))
				{
					this.OnMã_BánhChanging(value);
					this.SendPropertyChanging();
					this._Mã_Bánh = value;
					this.SendPropertyChanged("Mã_Bánh");
					this.OnMã_BánhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T2_Bảng_Bánh_T5_hóa_đơn", Storage="_T2_Bảng_Bánh", ThisKey="Mã_Bánh", OtherKey="Mã_Bánh", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public T2_Bảng_Bánh T2_Bảng_Bánh
		{
			get
			{
				return this._T2_Bảng_Bánh.Entity;
			}
			set
			{
				T2_Bảng_Bánh previousValue = this._T2_Bảng_Bánh.Entity;
				if (((previousValue != value) 
							|| (this._T2_Bảng_Bánh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._T2_Bảng_Bánh.Entity = null;
						previousValue.T5_hóa_đơns.Remove(this);
					}
					this._T2_Bảng_Bánh.Entity = value;
					if ((value != null))
					{
						value.T5_hóa_đơns.Add(this);
						this._Mã_Bánh = value.Mã_Bánh;
					}
					else
					{
						this._Mã_Bánh = default(string);
					}
					this.SendPropertyChanged("T2_Bảng_Bánh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T3_Bảng_KH_T5_hóa_đơn", Storage="_T3_Bảng_KH", ThisKey="Mã_KH", OtherKey="Mã_KH", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public T3_Bảng_KH T3_Bảng_KH
		{
			get
			{
				return this._T3_Bảng_KH.Entity;
			}
			set
			{
				T3_Bảng_KH previousValue = this._T3_Bảng_KH.Entity;
				if (((previousValue != value) 
							|| (this._T3_Bảng_KH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._T3_Bảng_KH.Entity = null;
						previousValue.T5_hóa_đơns.Remove(this);
					}
					this._T3_Bảng_KH.Entity = value;
					if ((value != null))
					{
						value.T5_hóa_đơns.Add(this);
						this._Mã_KH = value.Mã_KH;
					}
					else
					{
						this._Mã_KH = default(string);
					}
					this.SendPropertyChanged("T3_Bảng_KH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T4_Bảng_NV_T5_hóa_đơn", Storage="_T4_Bảng_NV", ThisKey="Mã_NV", OtherKey="Mã_NV", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public T4_Bảng_NV T4_Bảng_NV
		{
			get
			{
				return this._T4_Bảng_NV.Entity;
			}
			set
			{
				T4_Bảng_NV previousValue = this._T4_Bảng_NV.Entity;
				if (((previousValue != value) 
							|| (this._T4_Bảng_NV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._T4_Bảng_NV.Entity = null;
						previousValue.T5_hóa_đơns.Remove(this);
					}
					this._T4_Bảng_NV.Entity = value;
					if ((value != null))
					{
						value.T5_hóa_đơns.Add(this);
						this._Mã_NV = value.Mã_NV;
					}
					else
					{
						this._Mã_NV = default(string);
					}
					this.SendPropertyChanged("T4_Bảng_NV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
