#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom15_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanh")]
	public partial class DBQLBanhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBanhCookie(BanhCookie instance);
    partial void UpdateBanhCookie(BanhCookie instance);
    partial void DeleteBanhCookie(BanhCookie instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertBanhMan(BanhMan instance);
    partial void UpdateBanhMan(BanhMan instance);
    partial void DeleteBanhMan(BanhMan instance);
    partial void InsertBanhNgot(BanhNgot instance);
    partial void UpdateBanhNgot(BanhNgot instance);
    partial void DeleteBanhNgot(BanhNgot instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    #endregion
		
		public DBQLBanhDataContext() : 
				base(global::Nhom15_DAL.Properties.Settings.Default.QuanLyBanhConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBQLBanhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQLBanhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQLBanhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQLBanhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BanhCookie> BanhCookies
		{
			get
			{
				return this.GetTable<BanhCookie>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<BanhMan> BanhMans
		{
			get
			{
				return this.GetTable<BanhMan>();
			}
		}
		
		public System.Data.Linq.Table<BanhNgot> BanhNgots
		{
			get
			{
				return this.GetTable<BanhNgot>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sua_BanhCookie")]
		public int sua_BanhCookie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanh", DbType="Int")] System.Nullable<int> maBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenBanh", DbType="NVarChar(50)")] string tenBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTien", DbType="NVarChar(50)")] string giaTien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBanh, tenBanh, giaTien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoa_NhanVien")]
		public int xoa_NhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="Int")] System.Nullable<int> maNhanVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sua_BanhMan")]
		public int sua_BanhMan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanh", DbType="Int")] System.Nullable<int> maBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenBanh", DbType="NVarChar(50)")] string tenBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTien", DbType="NVarChar(50)")] string giaTien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBanh, tenBanh, giaTien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sua_BanhNgot")]
		public int sua_BanhNgot([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanh", DbType="Int")] System.Nullable<int> maBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenBanh", DbType="NVarChar(50)")] string tenBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTien", DbType="NVarChar(50)")] string giaTien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBanh, tenBanh, giaTien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sua_HoaDon")]
		public int sua_HoaDon([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHoaDon", DbType="Int")] System.Nullable<int> maHoaDon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="Int")] System.Nullable<int> maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanhMan", DbType="Int")] System.Nullable<int> maBanhMan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuongBanhMan", DbType="Int")] System.Nullable<int> soLuongBanhMan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanhNgot", DbType="Int")] System.Nullable<int> maBanhNgot, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuongBanhNgot", DbType="Int")] System.Nullable<int> soLuongBanhNgot, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanhCookie", DbType="Int")] System.Nullable<int> maBanhCookie, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuongBanhCookie", DbType="Int")] System.Nullable<int> soLuongBanhCookie, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayMuaHang", DbType="Date")] System.Nullable<System.DateTime> ngayMuaHang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHoaDon, maKhachHang, maNhanVien, maBanhMan, soLuongBanhMan, maBanhNgot, soLuongBanhNgot, maBanhCookie, soLuongBanhCookie, ngayMuaHang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sua_KhachHang")]
		public int sua_KhachHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NVarChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="NVarChar(50)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(50)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKhachHang, hoTen, ngaySinh, soDienThoai, gioiTinh, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sua_NhanVien")]
		public int sua_NhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="Int")] System.Nullable<int> maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NVarChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="NVarChar(50)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(50)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChucVu", DbType="NVarChar(50)")] string chucVu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenDangNhap", DbType="NVarChar(50)")] string tenDangNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhau", DbType="NVarChar(50)")] string matKhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, hoTen, ngaySinh, soDienThoai, gioiTinh, diaChi, chucVu, tenDangNhap, matKhau);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.them_BanhMan")]
		public int them_BanhMan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenBanh", DbType="NVarChar(50)")] string tenBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTien", DbType="NVarChar(50)")] string giaTien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenBanh, giaTien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.them_HoaDon")]
		public int them_HoaDon([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="Int")] System.Nullable<int> maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanhMan", DbType="Int")] System.Nullable<int> maBanhMan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuongBanhMan", DbType="Int")] System.Nullable<int> soLuongBanhMan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanhNgot", DbType="Int")] System.Nullable<int> maBanhNgot, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuongBanhNgot", DbType="Int")] System.Nullable<int> soLuongBanhNgot, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanhCookie", DbType="Int")] System.Nullable<int> maBanhCookie, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuongBanhCookie", DbType="Int")] System.Nullable<int> soLuongBanhCookie)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKhachHang, maNhanVien, maBanhMan, soLuongBanhMan, maBanhNgot, soLuongBanhNgot, maBanhCookie, soLuongBanhCookie);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.them_KhachHang")]
		public int them_KhachHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NVarChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="NVarChar(50)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(50)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoTen, ngaySinh, soDienThoai, gioiTinh, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.them_NhanVien")]
		public int them_NhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NVarChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="NVarChar(50)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(50)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChucVu", DbType="NVarChar(50)")] string chucVu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenDangNhap", DbType="NVarChar(50)")] string tenDangNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhau", DbType="NVarChar(50)")] string matKhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoTen, ngaySinh, soDienThoai, gioiTinh, diaChi, chucVu, tenDangNhap, matKhau);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoa_BanhCookie")]
		public int xoa_BanhCookie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanh", DbType="Int")] System.Nullable<int> maBanh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBanh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoa_BanhMan")]
		public int xoa_BanhMan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanh", DbType="Int")] System.Nullable<int> maBanh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBanh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoa_BanhNgot")]
		public int xoa_BanhNgot([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBanh", DbType="Int")] System.Nullable<int> maBanh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBanh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoa_DonHang")]
		public int xoa_DonHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDonHang", DbType="Int")] System.Nullable<int> maDonHang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maDonHang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoa_KhachHang")]
		public int xoa_KhachHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKhachHang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.new_MaBanhCookie", IsComposable=true)]
		public string new_MaBanhCookie()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.new_MaNhanVien", IsComposable=true)]
		public string new_MaNhanVien()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.new_MaBanhMan", IsComposable=true)]
		public string new_MaBanhMan()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.new_MaBanhNgot", IsComposable=true)]
		public string new_MaBanhNgot()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.new_MaHoaDon", IsComposable=true)]
		public System.Nullable<int> new_MaHoaDon()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.new_MaKhachHang", IsComposable=true)]
		public string new_MaKhachHang()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.them_BanhCookie")]
		public int them_BanhCookie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenBanh", DbType="NVarChar(50)")] string tenBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTien", DbType="NVarChar(50)")] string giaTien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenBanh, giaTien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.them_BanhNgot")]
		public int them_BanhNgot([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenBanh", DbType="NVarChar(50)")] string tenBanh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTien", DbType="NVarChar(50)")] string giaTien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenBanh, giaTien);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BanhCookie")]
	public partial class BanhCookie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBanh;
		
		private string _TenBanh;
		
		private string _GiaTien;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBanhChanging(int value);
    partial void OnMaBanhChanged();
    partial void OnTenBanhChanging(string value);
    partial void OnTenBanhChanged();
    partial void OnGiaTienChanging(string value);
    partial void OnGiaTienChanged();
    #endregion
		
		public BanhCookie()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBanh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBanh
		{
			get
			{
				return this._MaBanh;
			}
			set
			{
				if ((this._MaBanh != value))
				{
					this.OnMaBanhChanging(value);
					this.SendPropertyChanging();
					this._MaBanh = value;
					this.SendPropertyChanged("MaBanh");
					this.OnMaBanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBanh", DbType="NVarChar(50)")]
		public string TenBanh
		{
			get
			{
				return this._TenBanh;
			}
			set
			{
				if ((this._TenBanh != value))
				{
					this.OnTenBanhChanging(value);
					this.SendPropertyChanging();
					this._TenBanh = value;
					this.SendPropertyChanged("TenBanh");
					this.OnTenBanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="NVarChar(50)")]
		public string GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BanhCookie_HoaDon", Storage="_HoaDons", ThisKey="MaBanh", OtherKey="MaBanhCookie")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.BanhCookie = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.BanhCookie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _ChucVu;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BanhMan")]
	public partial class BanhMan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBanh;
		
		private string _TenBanh;
		
		private string _GiaTien;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBanhChanging(int value);
    partial void OnMaBanhChanged();
    partial void OnTenBanhChanging(string value);
    partial void OnTenBanhChanged();
    partial void OnGiaTienChanging(string value);
    partial void OnGiaTienChanged();
    #endregion
		
		public BanhMan()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBanh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBanh
		{
			get
			{
				return this._MaBanh;
			}
			set
			{
				if ((this._MaBanh != value))
				{
					this.OnMaBanhChanging(value);
					this.SendPropertyChanging();
					this._MaBanh = value;
					this.SendPropertyChanged("MaBanh");
					this.OnMaBanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBanh", DbType="NVarChar(50)")]
		public string TenBanh
		{
			get
			{
				return this._TenBanh;
			}
			set
			{
				if ((this._TenBanh != value))
				{
					this.OnTenBanhChanging(value);
					this.SendPropertyChanging();
					this._TenBanh = value;
					this.SendPropertyChanged("TenBanh");
					this.OnTenBanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="NVarChar(50)")]
		public string GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BanhMan_HoaDon", Storage="_HoaDons", ThisKey="MaBanh", OtherKey="MaBanhMan")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.BanhMan = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.BanhMan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BanhNgot")]
	public partial class BanhNgot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBanh;
		
		private string _TenBanh;
		
		private string _GiaTien;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBanhChanging(int value);
    partial void OnMaBanhChanged();
    partial void OnTenBanhChanging(string value);
    partial void OnTenBanhChanged();
    partial void OnGiaTienChanging(string value);
    partial void OnGiaTienChanged();
    #endregion
		
		public BanhNgot()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBanh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBanh
		{
			get
			{
				return this._MaBanh;
			}
			set
			{
				if ((this._MaBanh != value))
				{
					this.OnMaBanhChanging(value);
					this.SendPropertyChanging();
					this._MaBanh = value;
					this.SendPropertyChanged("MaBanh");
					this.OnMaBanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBanh", DbType="NVarChar(50)")]
		public string TenBanh
		{
			get
			{
				return this._TenBanh;
			}
			set
			{
				if ((this._TenBanh != value))
				{
					this.OnTenBanhChanging(value);
					this.SendPropertyChanging();
					this._TenBanh = value;
					this.SendPropertyChanged("TenBanh");
					this.OnTenBanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="NVarChar(50)")]
		public string GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BanhNgot_HoaDon", Storage="_HoaDons", ThisKey="MaBanh", OtherKey="MaBanhNgot")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.BanhNgot = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.BanhNgot = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHoaDon;
		
		private System.Nullable<int> _MaKhachHang;
		
		private System.Nullable<int> _MaNhanVien;
		
		private System.Nullable<int> _MaBanhMan;
		
		private System.Nullable<int> _SoLuongBanhMan;
		
		private System.Nullable<int> _MaBanhNgot;
		
		private System.Nullable<int> _SoLuongBanhNgot;
		
		private System.Nullable<int> _MaBanhCookie;
		
		private System.Nullable<int> _SoLuongBanhCookie;
		
		private System.Nullable<System.DateTime> _NgayMuaHang;
		
		private string _TongTien;
		
		private EntityRef<BanhCookie> _BanhCookie;
		
		private EntityRef<BanhMan> _BanhMan;
		
		private EntityRef<BanhNgot> _BanhNgot;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(int value);
    partial void OnMaHoaDonChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    partial void OnMaNhanVienChanging(System.Nullable<int> value);
    partial void OnMaNhanVienChanged();
    partial void OnMaBanhManChanging(System.Nullable<int> value);
    partial void OnMaBanhManChanged();
    partial void OnSoLuongBanhManChanging(System.Nullable<int> value);
    partial void OnSoLuongBanhManChanged();
    partial void OnMaBanhNgotChanging(System.Nullable<int> value);
    partial void OnMaBanhNgotChanged();
    partial void OnSoLuongBanhNgotChanging(System.Nullable<int> value);
    partial void OnSoLuongBanhNgotChanged();
    partial void OnMaBanhCookieChanging(System.Nullable<int> value);
    partial void OnMaBanhCookieChanged();
    partial void OnSoLuongBanhCookieChanging(System.Nullable<int> value);
    partial void OnSoLuongBanhCookieChanged();
    partial void OnNgayMuaHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMuaHangChanged();
    partial void OnTongTienChanging(string value);
    partial void OnTongTienChanged();
    #endregion
		
		public HoaDon()
		{
			this._BanhCookie = default(EntityRef<BanhCookie>);
			this._BanhMan = default(EntityRef<BanhMan>);
			this._BanhNgot = default(EntityRef<BanhNgot>);
			this._NhanVien = default(EntityRef<NhanVien>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int")]
		public System.Nullable<int> MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBanhMan", DbType="Int")]
		public System.Nullable<int> MaBanhMan
		{
			get
			{
				return this._MaBanhMan;
			}
			set
			{
				if ((this._MaBanhMan != value))
				{
					if (this._BanhMan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBanhManChanging(value);
					this.SendPropertyChanging();
					this._MaBanhMan = value;
					this.SendPropertyChanged("MaBanhMan");
					this.OnMaBanhManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongBanhMan", DbType="Int")]
		public System.Nullable<int> SoLuongBanhMan
		{
			get
			{
				return this._SoLuongBanhMan;
			}
			set
			{
				if ((this._SoLuongBanhMan != value))
				{
					this.OnSoLuongBanhManChanging(value);
					this.SendPropertyChanging();
					this._SoLuongBanhMan = value;
					this.SendPropertyChanged("SoLuongBanhMan");
					this.OnSoLuongBanhManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBanhNgot", DbType="Int")]
		public System.Nullable<int> MaBanhNgot
		{
			get
			{
				return this._MaBanhNgot;
			}
			set
			{
				if ((this._MaBanhNgot != value))
				{
					if (this._BanhNgot.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBanhNgotChanging(value);
					this.SendPropertyChanging();
					this._MaBanhNgot = value;
					this.SendPropertyChanged("MaBanhNgot");
					this.OnMaBanhNgotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongBanhNgot", DbType="Int")]
		public System.Nullable<int> SoLuongBanhNgot
		{
			get
			{
				return this._SoLuongBanhNgot;
			}
			set
			{
				if ((this._SoLuongBanhNgot != value))
				{
					this.OnSoLuongBanhNgotChanging(value);
					this.SendPropertyChanging();
					this._SoLuongBanhNgot = value;
					this.SendPropertyChanged("SoLuongBanhNgot");
					this.OnSoLuongBanhNgotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBanhCookie", DbType="Int")]
		public System.Nullable<int> MaBanhCookie
		{
			get
			{
				return this._MaBanhCookie;
			}
			set
			{
				if ((this._MaBanhCookie != value))
				{
					if (this._BanhCookie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBanhCookieChanging(value);
					this.SendPropertyChanging();
					this._MaBanhCookie = value;
					this.SendPropertyChanged("MaBanhCookie");
					this.OnMaBanhCookieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongBanhCookie", DbType="Int")]
		public System.Nullable<int> SoLuongBanhCookie
		{
			get
			{
				return this._SoLuongBanhCookie;
			}
			set
			{
				if ((this._SoLuongBanhCookie != value))
				{
					this.OnSoLuongBanhCookieChanging(value);
					this.SendPropertyChanging();
					this._SoLuongBanhCookie = value;
					this.SendPropertyChanged("SoLuongBanhCookie");
					this.OnSoLuongBanhCookieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuaHang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayMuaHang
		{
			get
			{
				return this._NgayMuaHang;
			}
			set
			{
				if ((this._NgayMuaHang != value))
				{
					this.OnNgayMuaHangChanging(value);
					this.SendPropertyChanging();
					this._NgayMuaHang = value;
					this.SendPropertyChanged("NgayMuaHang");
					this.OnNgayMuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="NVarChar(50)")]
		public string TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BanhCookie_HoaDon", Storage="_BanhCookie", ThisKey="MaBanhCookie", OtherKey="MaBanh", IsForeignKey=true, DeleteRule="CASCADE")]
		public BanhCookie BanhCookie
		{
			get
			{
				return this._BanhCookie.Entity;
			}
			set
			{
				BanhCookie previousValue = this._BanhCookie.Entity;
				if (((previousValue != value) 
							|| (this._BanhCookie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BanhCookie.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._BanhCookie.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaBanhCookie = value.MaBanh;
					}
					else
					{
						this._MaBanhCookie = default(Nullable<int>);
					}
					this.SendPropertyChanged("BanhCookie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BanhMan_HoaDon", Storage="_BanhMan", ThisKey="MaBanhMan", OtherKey="MaBanh", IsForeignKey=true, DeleteRule="CASCADE")]
		public BanhMan BanhMan
		{
			get
			{
				return this._BanhMan.Entity;
			}
			set
			{
				BanhMan previousValue = this._BanhMan.Entity;
				if (((previousValue != value) 
							|| (this._BanhMan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BanhMan.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._BanhMan.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaBanhMan = value.MaBanh;
					}
					else
					{
						this._MaBanhMan = default(Nullable<int>);
					}
					this.SendPropertyChanged("BanhMan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BanhNgot_HoaDon", Storage="_BanhNgot", ThisKey="MaBanhNgot", OtherKey="MaBanh", IsForeignKey=true, DeleteRule="CASCADE")]
		public BanhNgot BanhNgot
		{
			get
			{
				return this._BanhNgot.Entity;
			}
			set
			{
				BanhNgot previousValue = this._BanhNgot.Entity;
				if (((previousValue != value) 
							|| (this._BanhNgot.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BanhNgot.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._BanhNgot.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaBanhNgot = value.MaBanh;
					}
					else
					{
						this._MaBanhNgot = default(Nullable<int>);
					}
					this.SendPropertyChanged("BanhNgot");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true, DeleteRule="CASCADE")]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true, DeleteRule="CASCADE")]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachHang;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
}
#pragma warning restore 1591
